/**
* Movier
* This is the description of the called APIs
*
* OpenAPI spec version: 1.0.0
* Contact: gszasza1@gmail.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.baei7j.movier.network.models


/**
 * 
 * @param status_message 
 * @param status_code 
 */
data class ErrorMessage (
    val status_message: kotlin.String? = null,
    val status_code: kotlin.Long? = null
) {

}

