/**
* Movier
* This is the description of the called APIs
*
* OpenAPI spec version: 1.0.0
* Contact: gszasza1@gmail.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.baei7j.movier.network.models


/**
 * 
 * @param name 
 * @param id 
 */
data class Genre (
    val name: kotlin.String? = null,
    val id: kotlin.Int? = null
) {

}

