/**
* Movier
* This is the description of the called APIs
*
* OpenAPI spec version: 1.0.0
* Contact: gszasza1@gmail.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.baei7j.movier.network.models


/**
 * 
 * @param page 
 * @param total_results 
 * @param total_pages 
 * @param results 
 */
data class MovieList (
    val page: kotlin.Long? = null,
    val total_results: kotlin.Long? = null,
    val total_pages: kotlin.Long? = null,
    val results: kotlin.Array<Movie>? = null
) {

}

